### ISSUE TITLE
Add test for auto-complete

### ISSUE THREAD

**Issue by aik099** [minkphp/driver-testsuite#2]
The test needs to be added, that confirms, that auto-complete controls (e.g. jQueryUI.AutoComplete) for JS-enabled drivers works as expected:
- you can type a test
- a dropdown appears with a suggestions
- clicking on a suggestion puts it into the input
- [not sure about this one] the `change` event is fired

Right now due way how it's implemented at least for MinkSelenium2Driver this is a big issue.

**Comment by aik099** [comment]
With https://github.com/minkphp/MinkSelenium2Driver/pull/244 merged it might actually allow test added in here to pass, because then focus won't be moved away from the field (we're pressing TAB right now) and auto-complete control won't be closed.

**Comment by uuf6429** [comment]
@aik099 a bit of an old issue, but in principle I don't think this is doable.
There is no standard way how these custom controls would behave. Having such a test for a custom control will likely only work for that very specific implementation, and nothing else.

**Comment by aik099** [comment]
> There is no standard way how these custom controls would behave. Having such a test for a custom control will likely only work for that very specific implementation, and nothing else.

With the above-mentioned issue already merged and a slow auto-complete related issue rate (3 or fewer people since issue creation time had this problem) I think, that this issue can be safely closed.

> What probably makes more sense is to have a jQuery UI test suite developed and maintained by the jQuery folks, which would improve quality on both sides...

Maybe.
