### ISSUE TITLE
Test suite is not compatible with PhpUnit 8.0

### ISSUE THREAD

**Issue by oleg-andreyev** [minkphp/driver-testsuite#33]
https://travis-ci.org/oleg-andreyev/MinkSelenium2Driver/jobs/510999339

```
PHP Fatal error:  Declaration of Behat\Mink\Tests\Driver\SkippingUnsupportedTestCase::onNotSuccessfulTest(Throwable $e) must be compatible with PHPUnit\Framework\TestCase::onNotSuccessfulTest(Throwable $t): void in /home/travis/build/oleg-andreyev/MinkSelenium2Driver/vendor/mink/driver-testsuite/tests/SkippingUnsupportedTestCase.php on line 18
```

Supporting more and more versions of PHP is becoming quite painful, we already have https://github.com/minkphp/driver-testsuite/blob/d208035ccc5eaf4f1def0299a1979c1851a9a0fb/tests/SkippingUnsupportedTestCase.php#L9 which is trying to solve some issue with PHPUnit upgrade.

This repository does not define the exact version of PHPUnit it supports and relies on something that Travis-CI will provide. Currently, I think we need to define some version of PHPUnit which still support 5.3 and 7.x

**Comment by aik099** [comment]
Ha-ha. Supporting more and more PHPUnit versions is more painful, because on every major release BC breaks (in terms of public method signature change) occurs.

**Comment by oleg-andreyev** [comment]
Right, so instead of support so many versions of PHPUnit, I propose define PHPUnit version which supports our current requirements (PHP >= 5.4 or even >= 7.0).

**Comment by oleg-andreyev** [comment]
@stof what do you think about defining exact PHPUnit version?

**Comment by stof** [comment]
This has been solved
