### ISSUE TITLE
Testing "getText" driver method

### ISSUE THREAD

**Issue by aik099** [minkphp/driver-testsuite#98]
Recently we've changed `getText` method in Selenium-based drivers to allow getting the text of the invisible elements or elements that are visible, but Selenium thinks they're not:

* https://github.com/minkphp/webdriver-classic-driver/pull/32
* https://github.com/minkphp/MinkSelenium2Driver/pull/399

By doing so we've introduced a bug, that [Selenium code](https://github.com/SeleniumHQ/selenium/blob/a6b161a159c3d581b130f03a2e6e35f577f38dec/javascript/atoms/dom.js#L991) was solving for us before:

* trimming of the final text;
* replacing the symbol with `A0` ASCII code with a regular space.

While attempting to write a test about that I've found, that https://github.com/minkphp/MinkBrowserKitDriver implementation of `getText` don't support symbol with `A0` ASCII code at all.

I've written all the necessary code for :

* https://github.com/minkphp/driver-testsuite
* https://github.com/minkphp/webdriver-classic-driver
* https://github.com/minkphp/MinkSelenium2Driver
* https://github.com/minkphp/MinkBrowserKitDriver

Should I submit these PRs?

// cc: @stof , @uuf6429 , @mvorisek 

P.S.
As a bonus side effect the `innerText` does replace `<br>` with a regular space, which can result in spaces before/after the text, which we should also trim.

**Comment by mvorisek** [comment]
❤ and thank you for all your work!

**Comment by aik099** [comment]
### Example:

The text version of `div.test` element below is ` some text` (the non-breakable space present, but maybe GitHub can't display it as-is), while it should be `some text` (no leading/trailing space and no non-breakable space):
```
<div class="test"><img src="..."><br/>some&nbsp;text<br/></div>
```

**Comment by aik099** [comment]
Created associated PRs. Ready for review.

**Comment by aik099** [comment]
Closing, since everything is merged.
